# Generated by Django 5.2.2 on 2025-06-06 21:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('publication_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2100)], verbose_name='Год издания')),
                ('genre', models.CharField(choices=[('fiction', 'Художественная литература'), ('non_fiction', 'Нехудожественная литература'), ('science', 'Научная литература'), ('fantasy', 'Фэнтези'), ('sci_fi', 'Научная фантастика'), ('detective', 'Детектив'), ('romance', 'Романтика'), ('horror', 'Ужасы'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Жанр')),
                ('pages', models.PositiveIntegerField(verbose_name='Количество страниц')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Рейтинг')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='Бестселлер')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['-rating', 'title'],
            },
        ),
    ]
