version: '3.8'

services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always

  backend-service:
    build: ./backend
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      - db
    env_file:
      - ./.env
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=${POSTGRES_PORT}
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/templates/default.conf.template:/etc/nginx/templates/default.conf.template
      - static_volume:/static
    ports:
      - "80:80"
    depends_on:
      - backend-service
    restart: always

volumes:
  postgres_data:
  static_volume: